on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build_metrics:
    name: LangMetrics
    uses: lowlighter/metrics@v3.34
    with:
      filename: metrics.plugin.languages.svg
      token: ${{ secrets.METRICS_TOKEN }}
      base: ""
      plugin_languages: yes
      plugin_languages_ignored: >-
        html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
        gnuplot
      plugin_languages_limit: 4
