on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build_metrics:
    runs-on: ubuntu-22.04
    environment:
      name: Main
    permissions:
      contents: write
    steps:
      - name: LangMetrics
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            tex, less, qmake, lex, gnuplot
          plugin_languages_limit: 4
