on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
  schedule: [{cron: "0 0 * * *"}]

jobs:
  build_metrics:
    runs-on: ubuntu-22.04
    environment:
      name: Main
    permissions:
      contents: write
    steps:
      - name: LangMetrics
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            tex, less, qmake, lex, gnuplot
          plugin_languages_details: bytes-size, percentage
          plugin_languages_indepth: yes
          plugin_languages_threshold: 2%
          plugin_languages_limit: 10
      - name: CodeSnippet
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.code.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_code: yes
          plugin_code_languages: java, python, c++, c#, javascript
          plugin_code_load: 400
      - name: WebsitePeek
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.screenshot.svg
          token: NOT_NEEDED
          base: ""
          plugin_screenshot: yes
          plugin_screenshot_wait: 1500
          plugin_screenshot_title: Latest Website Build
          plugin_screenshot_url: https://voxacommunications-website.pages.dev/
